spring.application.name=fc-auth

# jpa common
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# jpa mysql
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/fc_auth
spring.datasource.username=postgres
spring.datasource.password=1234

# kakao
kakao.client_id: f171730519851e4e468a99a0b764d3fd
kakao.redirect_uri: http://localhost:8080/kakao/callback