# jpa common
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/fc_auth?useUnicode=true&serverTimezone=Asia/Seoul"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjdthddl

kakao.client_id: f171730519851e4e468a99a0b764d3fd
kakao.redirect_uri: http://localhost:8080/kakao/callback