# jpa common
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
  datasource:
    url: "jdbc:mysql://localhost:3306/fc_auth?useUnicode=true&serverTimezone=Asia/Seoul"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wjdthddl