spring.application.name=fc-auth

# jpa common
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

# jpa mysql
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/fc_auth
spring.datasource.username=postgres
spring.datasource.password=1234